// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meals.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addMealFavoriteCategory = `-- name: AddMealFavoriteCategory :exec
INSERT INTO meal_favorite_categories (meal_id, category_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddMealFavoriteCategoryParams struct {
	MealID     uuid.UUID `json:"meal_id"`
	CategoryID uuid.UUID `json:"category_id"`
}

func (q *Queries) AddMealFavoriteCategory(ctx context.Context, arg AddMealFavoriteCategoryParams) error {
	_, err := q.db.ExecContext(ctx, addMealFavoriteCategory, arg.MealID, arg.CategoryID)
	return err
}

const addMealLabelAssignment = `-- name: AddMealLabelAssignment :exec
INSERT INTO meal_label_assignments (meal_id, label_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddMealLabelAssignmentParams struct {
	MealID  uuid.UUID `json:"meal_id"`
	LabelID uuid.UUID `json:"label_id"`
}

func (q *Queries) AddMealLabelAssignment(ctx context.Context, arg AddMealLabelAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, addMealLabelAssignment, arg.MealID, arg.LabelID)
	return err
}

const clearMealFavoriteCategories = `-- name: ClearMealFavoriteCategories :exec
DELETE FROM meal_favorite_categories WHERE meal_id = $1
`

func (q *Queries) ClearMealFavoriteCategories(ctx context.Context, mealID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearMealFavoriteCategories, mealID)
	return err
}

const clearMealLabelAssignments = `-- name: ClearMealLabelAssignments :exec
DELETE FROM meal_label_assignments WHERE meal_id = $1
`

func (q *Queries) ClearMealLabelAssignments(ctx context.Context, mealID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearMealLabelAssignments, mealID)
	return err
}

const clearMealNutrientValues = `-- name: ClearMealNutrientValues :exec
DELETE FROM meal_nutrient_values WHERE meal_id = $1
`

func (q *Queries) ClearMealNutrientValues(ctx context.Context, mealID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearMealNutrientValues, mealID)
	return err
}

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (id, name, source, source_ref, recipe_url, serving_label, serving_amount, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, source, source_ref, recipe_url, serving_label, serving_amount, created_by, created_at, updated_at
`

type CreateMealParams struct {
	ID            uuid.UUID      `json:"id"`
	Name          string         `json:"name"`
	Source        string         `json:"source"`
	SourceRef     sql.NullString `json:"source_ref"`
	RecipeUrl     sql.NullString `json:"recipe_url"`
	ServingLabel  string         `json:"serving_label"`
	ServingAmount float64        `json:"serving_amount"`
	CreatedBy     uuid.NullUUID  `json:"created_by"`
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRowContext(ctx, createMeal,
		arg.ID,
		arg.Name,
		arg.Source,
		arg.SourceRef,
		arg.RecipeUrl,
		arg.ServingLabel,
		arg.ServingAmount,
		arg.CreatedBy,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.SourceRef,
		&i.RecipeUrl,
		&i.ServingLabel,
		&i.ServingAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMealLabel = `-- name: CreateMealLabel :one
INSERT INTO meal_labels (id, name, color, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, name, color, sort_order
`

type CreateMealLabelParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Color     string    `json:"color"`
	SortOrder int16     `json:"sort_order"`
}

func (q *Queries) CreateMealLabel(ctx context.Context, arg CreateMealLabelParams) (MealLabel, error) {
	row := q.db.QueryRowContext(ctx, createMealLabel,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.SortOrder,
	)
	var i MealLabel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
	)
	return i, err
}

const deleteMeal = `-- name: DeleteMeal :exec
DELETE FROM meals WHERE id = $1
`

func (q *Queries) DeleteMeal(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMeal, id)
	return err
}

const deleteMealLabel = `-- name: DeleteMealLabel :exec
DELETE FROM meal_labels WHERE id = $1
`

func (q *Queries) DeleteMealLabel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMealLabel, id)
	return err
}

const getManualMealByName = `-- name: GetManualMealByName :one
SELECT id, name, source, source_ref, recipe_url, serving_label, serving_amount, created_by, created_at, updated_at FROM meals WHERE source = 'manual' AND name = $1
`

// Export/import's natural-key lookup for manually-entered meals, which have
// no source_ref to match on (GetMealBySourceRef doesn't fit: source_ref is
// NULL for these, not an empty string).
func (q *Queries) GetManualMealByName(ctx context.Context, name string) (Meal, error) {
	row := q.db.QueryRowContext(ctx, getManualMealByName, name)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.SourceRef,
		&i.RecipeUrl,
		&i.ServingLabel,
		&i.ServingAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMeal = `-- name: GetMeal :one
SELECT id, name, source, source_ref, recipe_url, serving_label, serving_amount, created_by, created_at, updated_at FROM meals WHERE id = $1
`

func (q *Queries) GetMeal(ctx context.Context, id uuid.UUID) (Meal, error) {
	row := q.db.QueryRowContext(ctx, getMeal, id)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.SourceRef,
		&i.RecipeUrl,
		&i.ServingLabel,
		&i.ServingAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMealBySourceRef = `-- name: GetMealBySourceRef :one
SELECT id, name, source, source_ref, recipe_url, serving_label, serving_amount, created_by, created_at, updated_at FROM meals WHERE source = $1 AND source_ref = $2
`

type GetMealBySourceRefParams struct {
	Source    string         `json:"source"`
	SourceRef sql.NullString `json:"source_ref"`
}

func (q *Queries) GetMealBySourceRef(ctx context.Context, arg GetMealBySourceRefParams) (Meal, error) {
	row := q.db.QueryRowContext(ctx, getMealBySourceRef, arg.Source, arg.SourceRef)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.SourceRef,
		&i.RecipeUrl,
		&i.ServingLabel,
		&i.ServingAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMealLabelByName = `-- name: GetMealLabelByName :one
SELECT id, name, color, sort_order FROM meal_labels WHERE name = $1
`

// Export/import's natural-key lookup — a label's id means nothing across
// instances, but its name (already unique) does.
func (q *Queries) GetMealLabelByName(ctx context.Context, name string) (MealLabel, error) {
	row := q.db.QueryRowContext(ctx, getMealLabelByName, name)
	var i MealLabel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
	)
	return i, err
}

const isMealFavoriteForCategory = `-- name: IsMealFavoriteForCategory :one
SELECT EXISTS(
    SELECT 1 FROM meal_favorite_categories WHERE meal_id = $1 AND category_id = $2
)
`

type IsMealFavoriteForCategoryParams struct {
	MealID     uuid.UUID `json:"meal_id"`
	CategoryID uuid.UUID `json:"category_id"`
}

func (q *Queries) IsMealFavoriteForCategory(ctx context.Context, arg IsMealFavoriteForCategoryParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isMealFavoriteForCategory, arg.MealID, arg.CategoryID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFavoriteCategoriesForMeals = `-- name: ListFavoriteCategoriesForMeals :many
SELECT meal_favorite_categories.meal_id, meal_categories.id, meal_categories.name
FROM meal_favorite_categories
JOIN meal_categories ON meal_categories.id = meal_favorite_categories.category_id
WHERE meal_favorite_categories.meal_id = ANY($1::uuid[])
ORDER BY meal_categories.sort_order, meal_categories.name
`

type ListFavoriteCategoriesForMealsRow struct {
	MealID uuid.UUID `json:"meal_id"`
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
}

// Batched (not one query per meal) favorite-category lookup for a list of
// meals - the Meal Library list page's badges, fetched in one round trip
// regardless of how many meals are on the page.
func (q *Queries) ListFavoriteCategoriesForMeals(ctx context.Context, mealIds []uuid.UUID) ([]ListFavoriteCategoriesForMealsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFavoriteCategoriesForMeals, pq.Array(mealIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFavoriteCategoriesForMealsRow{}
	for rows.Next() {
		var i ListFavoriteCategoriesForMealsRow
		if err := rows.Scan(&i.MealID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavoriteCategoryIDsForMeal = `-- name: ListFavoriteCategoryIDsForMeal :many
SELECT category_id FROM meal_favorite_categories WHERE meal_id = $1
`

// The favorited category ids for one meal - used to pre-check the edit
// form's category checkboxes.
func (q *Queries) ListFavoriteCategoryIDsForMeal(ctx context.Context, mealID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listFavoriteCategoryIDsForMeal, mealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var category_id uuid.UUID
		if err := rows.Scan(&category_id); err != nil {
			return nil, err
		}
		items = append(items, category_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavoriteMealsForCategory = `-- name: ListFavoriteMealsForCategory :many
SELECT meals.id, meals.name, meals.source, meals.source_ref, meals.recipe_url, meals.serving_label, meals.serving_amount, meals.created_by, meals.created_at, meals.updated_at
FROM meals
JOIN meal_favorite_categories ON meal_favorite_categories.meal_id = meals.id
WHERE meal_favorite_categories.category_id = $1
ORDER BY meals.name
`

func (q *Queries) ListFavoriteMealsForCategory(ctx context.Context, categoryID uuid.UUID) ([]Meal, error) {
	rows, err := q.db.QueryContext(ctx, listFavoriteMealsForCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meal{}
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.SourceRef,
			&i.RecipeUrl,
			&i.ServingLabel,
			&i.ServingAmount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealLabelIDsForMeal = `-- name: ListMealLabelIDsForMeal :many
SELECT label_id FROM meal_label_assignments WHERE meal_id = $1
`

// The assigned label ids for one meal — used to pre-check the edit form's
// label checkboxes.
func (q *Queries) ListMealLabelIDsForMeal(ctx context.Context, mealID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listMealLabelIDsForMeal, mealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var label_id uuid.UUID
		if err := rows.Scan(&label_id); err != nil {
			return nil, err
		}
		items = append(items, label_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealLabels = `-- name: ListMealLabels :many
SELECT id, name, color, sort_order FROM meal_labels ORDER BY sort_order, name
`

func (q *Queries) ListMealLabels(ctx context.Context) ([]MealLabel, error) {
	rows, err := q.db.QueryContext(ctx, listMealLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealLabel{}
	for rows.Next() {
		var i MealLabel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealLabelsForMeals = `-- name: ListMealLabelsForMeals :many
SELECT meal_label_assignments.meal_id, meal_labels.id, meal_labels.name, meal_labels.color
FROM meal_label_assignments
JOIN meal_labels ON meal_labels.id = meal_label_assignments.label_id
WHERE meal_label_assignments.meal_id = ANY($1::uuid[])
ORDER BY meal_labels.sort_order, meal_labels.name
`

type ListMealLabelsForMealsRow struct {
	MealID uuid.UUID `json:"meal_id"`
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Color  string    `json:"color"`
}

// Batched (not one query per meal) label lookup for a list of meals — the
// Meal Library list page's badges, fetched in one round trip regardless of
// how many meals are on the page.
func (q *Queries) ListMealLabelsForMeals(ctx context.Context, mealIds []uuid.UUID) ([]ListMealLabelsForMealsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMealLabelsForMeals, pq.Array(mealIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMealLabelsForMealsRow{}
	for rows.Next() {
		var i ListMealLabelsForMealsRow
		if err := rows.Scan(
			&i.MealID,
			&i.ID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealNutrientValues = `-- name: ListMealNutrientValues :many
SELECT meal_nutrient_values.meal_id, meal_nutrient_values.nutrient_id, meal_nutrient_values.amount, nutrients.key, nutrients.display_name, nutrients.unit
FROM meal_nutrient_values
JOIN nutrients ON nutrients.id = meal_nutrient_values.nutrient_id
WHERE meal_id = $1
ORDER BY nutrients.sort_order
`

type ListMealNutrientValuesRow struct {
	MealID      uuid.UUID `json:"meal_id"`
	NutrientID  int16     `json:"nutrient_id"`
	Amount      float64   `json:"amount"`
	Key         string    `json:"key"`
	DisplayName string    `json:"display_name"`
	Unit        string    `json:"unit"`
}

func (q *Queries) ListMealNutrientValues(ctx context.Context, mealID uuid.UUID) ([]ListMealNutrientValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMealNutrientValues, mealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMealNutrientValuesRow{}
	for rows.Next() {
		var i ListMealNutrientValuesRow
		if err := rows.Scan(
			&i.MealID,
			&i.NutrientID,
			&i.Amount,
			&i.Key,
			&i.DisplayName,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeals = `-- name: ListMeals :many
SELECT id, name, source, source_ref, recipe_url, serving_label, serving_amount, created_by, created_at, updated_at FROM meals ORDER BY name LIMIT $1
`

func (q *Queries) ListMeals(ctx context.Context, limitCount int32) ([]Meal, error) {
	rows, err := q.db.QueryContext(ctx, listMeals, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meal{}
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.SourceRef,
			&i.RecipeUrl,
			&i.ServingLabel,
			&i.ServingAmount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealsByLabel = `-- name: ListMealsByLabel :many
SELECT meals.id, meals.name, meals.source, meals.source_ref, meals.recipe_url, meals.serving_label, meals.serving_amount, meals.created_by, meals.created_at, meals.updated_at
FROM meals
JOIN meal_label_assignments ON meal_label_assignments.meal_id = meals.id
WHERE meal_label_assignments.label_id = $1
ORDER BY meals.name
LIMIT $2
`

type ListMealsByLabelParams struct {
	LabelID    uuid.UUID `json:"label_id"`
	LimitCount int32     `json:"limit_count"`
}

func (q *Queries) ListMealsByLabel(ctx context.Context, arg ListMealsByLabelParams) ([]Meal, error) {
	rows, err := q.db.QueryContext(ctx, listMealsByLabel, arg.LabelID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meal{}
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.SourceRef,
			&i.RecipeUrl,
			&i.ServingLabel,
			&i.ServingAmount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMealFavoriteCategory = `-- name: RemoveMealFavoriteCategory :exec
DELETE FROM meal_favorite_categories WHERE meal_id = $1 AND category_id = $2
`

type RemoveMealFavoriteCategoryParams struct {
	MealID     uuid.UUID `json:"meal_id"`
	CategoryID uuid.UUID `json:"category_id"`
}

func (q *Queries) RemoveMealFavoriteCategory(ctx context.Context, arg RemoveMealFavoriteCategoryParams) error {
	_, err := q.db.ExecContext(ctx, removeMealFavoriteCategory, arg.MealID, arg.CategoryID)
	return err
}

const searchMeals = `-- name: SearchMeals :many
SELECT id, name, source, source_ref, recipe_url, serving_label, serving_amount, created_by, created_at, updated_at
FROM meals
WHERE word_similarity($1::text, name) > 0.3
ORDER BY word_similarity($1::text, name) DESC
LIMIT $2
`

type SearchMealsParams struct {
	Query      string `json:"query"`
	LimitCount int32  `json:"limit_count"`
}

// word_similarity (not whole-string similarity/%) so a typo in one word of a
// multi-word name (e.g. "chikcen" against "Chicken & Rice") still matches —
// whole-string trigram similarity dilutes a single-word typo's score too
// much once other words are mixed in, and silently returns nothing at the
// default 0.3 threshold. 0.3 against the best-matching word instead gives a
// clean separation between typo'd/partial matches and unrelated queries.
func (q *Queries) SearchMeals(ctx context.Context, arg SearchMealsParams) ([]Meal, error) {
	rows, err := q.db.QueryContext(ctx, searchMeals, arg.Query, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meal{}
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.SourceRef,
			&i.RecipeUrl,
			&i.ServingLabel,
			&i.ServingAmount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMealsByLabel = `-- name: SearchMealsByLabel :many
SELECT meals.id, meals.name, meals.source, meals.source_ref, meals.recipe_url, meals.serving_label, meals.serving_amount, meals.created_by, meals.created_at, meals.updated_at
FROM meals
JOIN meal_label_assignments ON meal_label_assignments.meal_id = meals.id
WHERE meal_label_assignments.label_id = $1
  AND word_similarity($2::text, meals.name) > 0.3
ORDER BY word_similarity($2::text, meals.name) DESC
LIMIT $3
`

type SearchMealsByLabelParams struct {
	LabelID    uuid.UUID `json:"label_id"`
	Query      string    `json:"query"`
	LimitCount int32     `json:"limit_count"`
}

// See SearchMeals for why word_similarity rather than whole-string.
func (q *Queries) SearchMealsByLabel(ctx context.Context, arg SearchMealsByLabelParams) ([]Meal, error) {
	rows, err := q.db.QueryContext(ctx, searchMealsByLabel, arg.LabelID, arg.Query, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meal{}
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.SourceRef,
			&i.RecipeUrl,
			&i.ServingLabel,
			&i.ServingAmount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMealNutrientValue = `-- name: SetMealNutrientValue :exec
INSERT INTO meal_nutrient_values (meal_id, nutrient_id, amount)
VALUES ($1, $2, $3)
ON CONFLICT (meal_id, nutrient_id) DO UPDATE SET amount = EXCLUDED.amount
`

type SetMealNutrientValueParams struct {
	MealID     uuid.UUID `json:"meal_id"`
	NutrientID int16     `json:"nutrient_id"`
	Amount     float64   `json:"amount"`
}

func (q *Queries) SetMealNutrientValue(ctx context.Context, arg SetMealNutrientValueParams) error {
	_, err := q.db.ExecContext(ctx, setMealNutrientValue, arg.MealID, arg.NutrientID, arg.Amount)
	return err
}

const updateMeal = `-- name: UpdateMeal :one
UPDATE meals
SET name = $1, recipe_url = $2, serving_label = $3, serving_amount = $4, updated_at = now()
WHERE id = $5
RETURNING id, name, source, source_ref, recipe_url, serving_label, serving_amount, created_by, created_at, updated_at
`

type UpdateMealParams struct {
	Name          string         `json:"name"`
	RecipeUrl     sql.NullString `json:"recipe_url"`
	ServingLabel  string         `json:"serving_label"`
	ServingAmount float64        `json:"serving_amount"`
	ID            uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateMeal(ctx context.Context, arg UpdateMealParams) (Meal, error) {
	row := q.db.QueryRowContext(ctx, updateMeal,
		arg.Name,
		arg.RecipeUrl,
		arg.ServingLabel,
		arg.ServingAmount,
		arg.ID,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.SourceRef,
		&i.RecipeUrl,
		&i.ServingLabel,
		&i.ServingAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMealLabel = `-- name: UpdateMealLabel :one
UPDATE meal_labels SET name = $1, color = $2 WHERE id = $3 RETURNING id, name, color, sort_order
`

type UpdateMealLabelParams struct {
	Name  string    `json:"name"`
	Color string    `json:"color"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateMealLabel(ctx context.Context, arg UpdateMealLabelParams) (MealLabel, error) {
	row := q.db.QueryRowContext(ctx, updateMealLabel, arg.Name, arg.Color, arg.ID)
	var i MealLabel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
	)
	return i, err
}

const upsertMealBySourceRef = `-- name: UpsertMealBySourceRef :one
INSERT INTO meals (id, name, source, source_ref, recipe_url, serving_label, serving_amount, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (source, source_ref) WHERE source_ref IS NOT NULL
DO UPDATE SET name = EXCLUDED.name, recipe_url = EXCLUDED.recipe_url,
              serving_label = EXCLUDED.serving_label, serving_amount = EXCLUDED.serving_amount,
              updated_at = now()
RETURNING id, name, source, source_ref, recipe_url, serving_label, serving_amount, created_by, created_at, updated_at
`

type UpsertMealBySourceRefParams struct {
	ID            uuid.UUID      `json:"id"`
	Name          string         `json:"name"`
	Source        string         `json:"source"`
	SourceRef     sql.NullString `json:"source_ref"`
	RecipeUrl     sql.NullString `json:"recipe_url"`
	ServingLabel  string         `json:"serving_label"`
	ServingAmount float64        `json:"serving_amount"`
	CreatedBy     uuid.NullUUID  `json:"created_by"`
}

// id is only used for a brand-new row — on conflict, the existing row keeps
// its original id (DO UPDATE below never touches the id column).
func (q *Queries) UpsertMealBySourceRef(ctx context.Context, arg UpsertMealBySourceRefParams) (Meal, error) {
	row := q.db.QueryRowContext(ctx, upsertMealBySourceRef,
		arg.ID,
		arg.Name,
		arg.Source,
		arg.SourceRef,
		arg.RecipeUrl,
		arg.ServingLabel,
		arg.ServingAmount,
		arg.CreatedBy,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.SourceRef,
		&i.RecipeUrl,
		&i.ServingLabel,
		&i.ServingAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
