// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nutrients.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createMealCategory = `-- name: CreateMealCategory :one
INSERT INTO meal_categories (id, name, sort_order)
VALUES ($1, $2, $3)
RETURNING id, name, sort_order
`

type CreateMealCategoryParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	SortOrder int16     `json:"sort_order"`
}

func (q *Queries) CreateMealCategory(ctx context.Context, arg CreateMealCategoryParams) (MealCategory, error) {
	row := q.db.QueryRowContext(ctx, createMealCategory, arg.ID, arg.Name, arg.SortOrder)
	var i MealCategory
	err := row.Scan(&i.ID, &i.Name, &i.SortOrder)
	return i, err
}

const deleteMealCategory = `-- name: DeleteMealCategory :exec
DELETE FROM meal_categories WHERE id = $1
`

func (q *Queries) DeleteMealCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMealCategory, id)
	return err
}

const getAppSetting = `-- name: GetAppSetting :one
SELECT value FROM app_settings WHERE key = $1
`

func (q *Queries) GetAppSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAppSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getMealCategoryByName = `-- name: GetMealCategoryByName :one
SELECT id, name, sort_order FROM meal_categories WHERE name = $1
`

// Export/import's natural-key lookup — a category's id means nothing across
// instances, but its name (already unique) does.
func (q *Queries) GetMealCategoryByName(ctx context.Context, name string) (MealCategory, error) {
	row := q.db.QueryRowContext(ctx, getMealCategoryByName, name)
	var i MealCategory
	err := row.Scan(&i.ID, &i.Name, &i.SortOrder)
	return i, err
}

const listAppSettings = `-- name: ListAppSettings :many
SELECT key, value FROM app_settings ORDER BY key
`

func (q *Queries) ListAppSettings(ctx context.Context) ([]AppSetting, error) {
	rows, err := q.db.QueryContext(ctx, listAppSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSetting{}
	for rows.Next() {
		var i AppSetting
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealCategories = `-- name: ListMealCategories :many
SELECT id, name, sort_order FROM meal_categories ORDER BY sort_order
`

func (q *Queries) ListMealCategories(ctx context.Context) ([]MealCategory, error) {
	rows, err := q.db.QueryContext(ctx, listMealCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealCategory{}
	for rows.Next() {
		var i MealCategory
		if err := rows.Scan(&i.ID, &i.Name, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNutrients = `-- name: ListNutrients :many
SELECT id, key, display_name, unit, sort_order FROM nutrients ORDER BY sort_order
`

func (q *Queries) ListNutrients(ctx context.Context) ([]Nutrient, error) {
	rows, err := q.db.QueryContext(ctx, listNutrients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Nutrient{}
	for rows.Next() {
		var i Nutrient
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.DisplayName,
			&i.Unit,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAppSetting = `-- name: SetAppSetting :exec
INSERT INTO app_settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
`

type SetAppSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetAppSetting(ctx context.Context, arg SetAppSettingParams) error {
	_, err := q.db.ExecContext(ctx, setAppSetting, arg.Key, arg.Value)
	return err
}

const updateMealCategory = `-- name: UpdateMealCategory :one
UPDATE meal_categories SET name = $1, sort_order = $2 WHERE id = $3
RETURNING id, name, sort_order
`

type UpdateMealCategoryParams struct {
	Name      string    `json:"name"`
	SortOrder int16     `json:"sort_order"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) UpdateMealCategory(ctx context.Context, arg UpdateMealCategoryParams) (MealCategory, error) {
	row := q.db.QueryRowContext(ctx, updateMealCategory, arg.Name, arg.SortOrder, arg.ID)
	var i MealCategory
	err := row.Scan(&i.ID, &i.Name, &i.SortOrder)
	return i, err
}
