// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addDayPlanItem = `-- name: AddDayPlanItem :one
INSERT INTO day_plan_items (id, day_plan_id, category_id, meal_id, quantity, sort_order)
VALUES (
    $1, $2, $3, $4, $5,
    COALESCE(
        (SELECT MAX(sort_order) + 1 FROM day_plan_items WHERE day_plan_id = $2 AND category_id = $3),
        0
    )
)
RETURNING id, day_plan_id, category_id, meal_id, quantity, sort_order
`

type AddDayPlanItemParams struct {
	ID         uuid.UUID `json:"id"`
	DayPlanID  uuid.UUID `json:"day_plan_id"`
	CategoryID uuid.UUID `json:"category_id"`
	MealID     uuid.UUID `json:"meal_id"`
	Quantity   float64   `json:"quantity"`
}

// sort_order is computed in the same statement as the insert rather than a
// separate SELECT MAX + application-side increment, so normal sequential
// adds (the common case) always get a distinct, increasing sort_order.
func (q *Queries) AddDayPlanItem(ctx context.Context, arg AddDayPlanItemParams) (DayPlanItem, error) {
	row := q.db.QueryRowContext(ctx, addDayPlanItem,
		arg.ID,
		arg.DayPlanID,
		arg.CategoryID,
		arg.MealID,
		arg.Quantity,
	)
	var i DayPlanItem
	err := row.Scan(
		&i.ID,
		&i.DayPlanID,
		&i.CategoryID,
		&i.MealID,
		&i.Quantity,
		&i.SortOrder,
	)
	return i, err
}

const addDefaultDayItem = `-- name: AddDefaultDayItem :one
INSERT INTO default_day_items (id, user_id, category_id, meal_id, quantity, sort_order)
VALUES (
    $1, $2, $3, $4, $5,
    COALESCE(
        (SELECT MAX(sort_order) + 1 FROM default_day_items WHERE user_id = $2 AND category_id = $3),
        0
    )
)
RETURNING id, user_id, category_id, meal_id, quantity, sort_order
`

type AddDefaultDayItemParams struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	CategoryID uuid.UUID `json:"category_id"`
	MealID     uuid.UUID `json:"meal_id"`
	Quantity   float64   `json:"quantity"`
}

func (q *Queries) AddDefaultDayItem(ctx context.Context, arg AddDefaultDayItemParams) (DefaultDayItem, error) {
	row := q.db.QueryRowContext(ctx, addDefaultDayItem,
		arg.ID,
		arg.UserID,
		arg.CategoryID,
		arg.MealID,
		arg.Quantity,
	)
	var i DefaultDayItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.MealID,
		&i.Quantity,
		&i.SortOrder,
	)
	return i, err
}

const getDayPlan = `-- name: GetDayPlan :one
SELECT id, user_id, plan_date FROM day_plans WHERE user_id = $1 AND plan_date = $2
`

type GetDayPlanParams struct {
	UserID   uuid.UUID `json:"user_id"`
	PlanDate time.Time `json:"plan_date"`
}

func (q *Queries) GetDayPlan(ctx context.Context, arg GetDayPlanParams) (DayPlan, error) {
	row := q.db.QueryRowContext(ctx, getDayPlan, arg.UserID, arg.PlanDate)
	var i DayPlan
	err := row.Scan(&i.ID, &i.UserID, &i.PlanDate)
	return i, err
}

const getDayPlanItemOwner = `-- name: GetDayPlanItemOwner :one
SELECT day_plans.user_id, day_plans.id AS day_plan_id
FROM day_plan_items
JOIN day_plans ON day_plans.id = day_plan_items.day_plan_id
WHERE day_plan_items.id = $1
`

type GetDayPlanItemOwnerRow struct {
	UserID    uuid.UUID `json:"user_id"`
	DayPlanID uuid.UUID `json:"day_plan_id"`
}

// Used to authorize item mutations: confirms which user's day plan an item
// belongs to before a delete/quantity-update is allowed to touch it.
func (q *Queries) GetDayPlanItemOwner(ctx context.Context, id uuid.UUID) (GetDayPlanItemOwnerRow, error) {
	row := q.db.QueryRowContext(ctx, getDayPlanItemOwner, id)
	var i GetDayPlanItemOwnerRow
	err := row.Scan(&i.UserID, &i.DayPlanID)
	return i, err
}

const getDayPlanTotals = `-- name: GetDayPlanTotals :many
SELECT nutrients.id AS nutrient_id, nutrients.key, nutrients.display_name, nutrients.unit,
       COALESCE(SUM(meal_nutrient_values.amount * day_plan_items.quantity), 0)::numeric AS total
FROM day_plan_items
JOIN meal_nutrient_values ON meal_nutrient_values.meal_id = day_plan_items.meal_id
JOIN nutrients ON nutrients.id = meal_nutrient_values.nutrient_id
WHERE day_plan_items.day_plan_id = $1
GROUP BY nutrients.id, nutrients.key, nutrients.display_name, nutrients.unit, nutrients.sort_order
ORDER BY nutrients.sort_order
`

type GetDayPlanTotalsRow struct {
	NutrientID  int16   `json:"nutrient_id"`
	Key         string  `json:"key"`
	DisplayName string  `json:"display_name"`
	Unit        string  `json:"unit"`
	Total       float64 `json:"total"`
}

func (q *Queries) GetDayPlanTotals(ctx context.Context, dayPlanID uuid.UUID) ([]GetDayPlanTotalsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDayPlanTotals, dayPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDayPlanTotalsRow{}
	for rows.Next() {
		var i GetDayPlanTotalsRow
		if err := rows.Scan(
			&i.NutrientID,
			&i.Key,
			&i.DisplayName,
			&i.Unit,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateDayPlan = `-- name: GetOrCreateDayPlan :one
INSERT INTO day_plans (id, user_id, plan_date)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, plan_date) DO UPDATE SET plan_date = EXCLUDED.plan_date
RETURNING id, user_id, plan_date
`

type GetOrCreateDayPlanParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	PlanDate time.Time `json:"plan_date"`
}

// id is only used for a brand-new row — on conflict, the existing row keeps
// its original id.
func (q *Queries) GetOrCreateDayPlan(ctx context.Context, arg GetOrCreateDayPlanParams) (DayPlan, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateDayPlan, arg.ID, arg.UserID, arg.PlanDate)
	var i DayPlan
	err := row.Scan(&i.ID, &i.UserID, &i.PlanDate)
	return i, err
}

const getUserNutrientGoals = `-- name: GetUserNutrientGoals :many
SELECT user_nutrient_goals.user_id, user_nutrient_goals.nutrient_id, user_nutrient_goals.min_value, user_nutrient_goals.max_value, user_nutrient_goals.ideal_min, user_nutrient_goals.ideal_max, nutrients.key, nutrients.display_name, nutrients.unit
FROM user_nutrient_goals
JOIN nutrients ON nutrients.id = user_nutrient_goals.nutrient_id
WHERE user_id = $1
ORDER BY nutrients.sort_order
`

type GetUserNutrientGoalsRow struct {
	UserID      uuid.UUID `json:"user_id"`
	NutrientID  int16     `json:"nutrient_id"`
	MinValue    *float64  `json:"min_value"`
	MaxValue    *float64  `json:"max_value"`
	IdealMin    *float64  `json:"ideal_min"`
	IdealMax    *float64  `json:"ideal_max"`
	Key         string    `json:"key"`
	DisplayName string    `json:"display_name"`
	Unit        string    `json:"unit"`
}

func (q *Queries) GetUserNutrientGoals(ctx context.Context, userID uuid.UUID) ([]GetUserNutrientGoalsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserNutrientGoals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserNutrientGoalsRow{}
	for rows.Next() {
		var i GetUserNutrientGoalsRow
		if err := rows.Scan(
			&i.UserID,
			&i.NutrientID,
			&i.MinValue,
			&i.MaxValue,
			&i.IdealMin,
			&i.IdealMax,
			&i.Key,
			&i.DisplayName,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDayPlanItems = `-- name: ListDayPlanItems :many
SELECT day_plan_items.id, day_plan_items.day_plan_id, day_plan_items.category_id, day_plan_items.meal_id, day_plan_items.quantity, day_plan_items.sort_order, meals.name AS meal_name, meal_categories.name AS category_name
FROM day_plan_items
JOIN meals ON meals.id = day_plan_items.meal_id
JOIN meal_categories ON meal_categories.id = day_plan_items.category_id
WHERE day_plan_id = $1
ORDER BY meal_categories.sort_order, day_plan_items.sort_order, day_plan_items.id
`

type ListDayPlanItemsRow struct {
	ID           uuid.UUID `json:"id"`
	DayPlanID    uuid.UUID `json:"day_plan_id"`
	CategoryID   uuid.UUID `json:"category_id"`
	MealID       uuid.UUID `json:"meal_id"`
	Quantity     float64   `json:"quantity"`
	SortOrder    int16     `json:"sort_order"`
	MealName     string    `json:"meal_name"`
	CategoryName string    `json:"category_name"`
}

// Ordered by id as a final tiebreaker (not just category/item sort_order) so
// that two items which happen to land on the same sort_order — e.g. from a
// rare concurrent-insert race — still get a stable, repeatable order across
// queries instead of appearing to reshuffle on every page load.
func (q *Queries) ListDayPlanItems(ctx context.Context, dayPlanID uuid.UUID) ([]ListDayPlanItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDayPlanItems, dayPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDayPlanItemsRow{}
	for rows.Next() {
		var i ListDayPlanItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.DayPlanID,
			&i.CategoryID,
			&i.MealID,
			&i.Quantity,
			&i.SortOrder,
			&i.MealName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDayPlansInRange = `-- name: ListDayPlansInRange :many
SELECT id, user_id, plan_date FROM day_plans
WHERE user_id = $1 AND plan_date BETWEEN $2 AND $3
ORDER BY plan_date
`

type ListDayPlansInRangeParams struct {
	UserID     uuid.UUID `json:"user_id"`
	PlanDate   time.Time `json:"plan_date"`
	PlanDate_2 time.Time `json:"plan_date_2"`
}

func (q *Queries) ListDayPlansInRange(ctx context.Context, arg ListDayPlansInRangeParams) ([]DayPlan, error) {
	rows, err := q.db.QueryContext(ctx, listDayPlansInRange, arg.UserID, arg.PlanDate, arg.PlanDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DayPlan{}
	for rows.Next() {
		var i DayPlan
		if err := rows.Scan(&i.ID, &i.UserID, &i.PlanDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDefaultDayItems = `-- name: ListDefaultDayItems :many
SELECT default_day_items.id, default_day_items.user_id, default_day_items.category_id, default_day_items.meal_id, default_day_items.quantity, default_day_items.sort_order, meals.name AS meal_name
FROM default_day_items
JOIN meals ON meals.id = default_day_items.meal_id
WHERE user_id = $1
ORDER BY category_id, sort_order, default_day_items.id
`

type ListDefaultDayItemsRow struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	CategoryID uuid.UUID `json:"category_id"`
	MealID     uuid.UUID `json:"meal_id"`
	Quantity   float64   `json:"quantity"`
	SortOrder  int16     `json:"sort_order"`
	MealName   string    `json:"meal_name"`
}

func (q *Queries) ListDefaultDayItems(ctx context.Context, userID uuid.UUID) ([]ListDefaultDayItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDefaultDayItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDefaultDayItemsRow{}
	for rows.Next() {
		var i ListDefaultDayItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.MealID,
			&i.Quantity,
			&i.SortOrder,
			&i.MealName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDayPlanItem = `-- name: RemoveDayPlanItem :exec
DELETE FROM day_plan_items WHERE id = $1
`

func (q *Queries) RemoveDayPlanItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeDayPlanItem, id)
	return err
}

const removeDefaultDayItem = `-- name: RemoveDefaultDayItem :execrows
DELETE FROM default_day_items WHERE id = $1 AND user_id = $2
`

type RemoveDefaultDayItemParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveDefaultDayItem(ctx context.Context, arg RemoveDefaultDayItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeDefaultDayItem, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setUserNutrientGoal = `-- name: SetUserNutrientGoal :exec
INSERT INTO user_nutrient_goals (user_id, nutrient_id, min_value, max_value, ideal_min, ideal_max)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, nutrient_id) DO UPDATE SET
    min_value = EXCLUDED.min_value, max_value = EXCLUDED.max_value,
    ideal_min = EXCLUDED.ideal_min, ideal_max = EXCLUDED.ideal_max
`

type SetUserNutrientGoalParams struct {
	UserID     uuid.UUID `json:"user_id"`
	NutrientID int16     `json:"nutrient_id"`
	MinValue   *float64  `json:"min_value"`
	MaxValue   *float64  `json:"max_value"`
	IdealMin   *float64  `json:"ideal_min"`
	IdealMax   *float64  `json:"ideal_max"`
}

func (q *Queries) SetUserNutrientGoal(ctx context.Context, arg SetUserNutrientGoalParams) error {
	_, err := q.db.ExecContext(ctx, setUserNutrientGoal,
		arg.UserID,
		arg.NutrientID,
		arg.MinValue,
		arg.MaxValue,
		arg.IdealMin,
		arg.IdealMax,
	)
	return err
}

const updateDayPlanItemQuantity = `-- name: UpdateDayPlanItemQuantity :exec
UPDATE day_plan_items SET quantity = $1 WHERE id = $2
`

type UpdateDayPlanItemQuantityParams struct {
	Quantity float64   `json:"quantity"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateDayPlanItemQuantity(ctx context.Context, arg UpdateDayPlanItemQuantityParams) error {
	_, err := q.db.ExecContext(ctx, updateDayPlanItemQuantity, arg.Quantity, arg.ID)
	return err
}
