// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AppSetting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type DayPlan struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	PlanDate time.Time `json:"plan_date"`
}

type DayPlanItem struct {
	ID         uuid.UUID `json:"id"`
	DayPlanID  uuid.UUID `json:"day_plan_id"`
	CategoryID uuid.UUID `json:"category_id"`
	MealID     uuid.UUID `json:"meal_id"`
	Quantity   float64   `json:"quantity"`
	SortOrder  int16     `json:"sort_order"`
}

type DefaultDayItem struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	CategoryID uuid.UUID `json:"category_id"`
	MealID     uuid.UUID `json:"meal_id"`
	Quantity   float64   `json:"quantity"`
	SortOrder  int16     `json:"sort_order"`
}

type Meal struct {
	ID            uuid.UUID      `json:"id"`
	Name          string         `json:"name"`
	Source        string         `json:"source"`
	SourceRef     sql.NullString `json:"source_ref"`
	RecipeUrl     sql.NullString `json:"recipe_url"`
	ServingLabel  string         `json:"serving_label"`
	ServingAmount float64        `json:"serving_amount"`
	CreatedBy     uuid.NullUUID  `json:"created_by"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	IsFavorite    bool           `json:"is_favorite"`
}

type MealCategory struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	SortOrder int16     `json:"sort_order"`
}

type MealLabel struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Color     string    `json:"color"`
	SortOrder int16     `json:"sort_order"`
}

type MealLabelAssignment struct {
	MealID  uuid.UUID `json:"meal_id"`
	LabelID uuid.UUID `json:"label_id"`
}

type MealNutrientValue struct {
	MealID     uuid.UUID `json:"meal_id"`
	NutrientID int16     `json:"nutrient_id"`
	Amount     float64   `json:"amount"`
}

type MealsFt struct {
	Name string `json:"name"`
}

type Nutrient struct {
	ID          int16  `json:"id"`
	Key         string `json:"key"`
	DisplayName string `json:"display_name"`
	Unit        string `json:"unit"`
	SortOrder   int16  `json:"sort_order"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	OidcSubject  sql.NullString `json:"oidc_subject"`
	Email        string         `json:"email"`
	DisplayName  sql.NullString `json:"display_name"`
	CreatedAt    time.Time      `json:"created_at"`
	PasswordHash sql.NullString `json:"password_hash"`
	IsAdmin      bool           `json:"is_admin"`
}

type UserNutrientGoal struct {
	UserID     uuid.UUID `json:"user_id"`
	NutrientID int16     `json:"nutrient_id"`
	MinValue   *float64  `json:"min_value"`
	MaxValue   *float64  `json:"max_value"`
	IdealMin   *float64  `json:"ideal_min"`
	IdealMax   *float64  `json:"ideal_max"`
}
