// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	// sort_order is computed in the same statement as the insert rather than a
	// separate SELECT MAX + application-side increment, so normal sequential
	// adds (the common case) always get a distinct, increasing sort_order.
	AddDayPlanItem(ctx context.Context, arg AddDayPlanItemParams) (DayPlanItem, error)
	AddDefaultDayItem(ctx context.Context, arg AddDefaultDayItemParams) (DefaultDayItem, error)
	AddMealFavoriteCategory(ctx context.Context, arg AddMealFavoriteCategoryParams) error
	AddMealLabelAssignment(ctx context.Context, arg AddMealLabelAssignmentParams) error
	ClearMealFavoriteCategories(ctx context.Context, mealID uuid.UUID) error
	ClearMealLabelAssignments(ctx context.Context, mealID uuid.UUID) error
	ClearMealNutrientValues(ctx context.Context, mealID uuid.UUID) error
	CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error)
	CreateMealCategory(ctx context.Context, arg CreateMealCategoryParams) (MealCategory, error)
	CreateMealLabel(ctx context.Context, arg CreateMealLabelParams) (MealLabel, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteMeal(ctx context.Context, id uuid.UUID) error
	DeleteMealCategory(ctx context.Context, id uuid.UUID) error
	DeleteMealLabel(ctx context.Context, id uuid.UUID) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	GetAppSetting(ctx context.Context, key string) (string, error)
	GetDayPlan(ctx context.Context, arg GetDayPlanParams) (DayPlan, error)
	// Used to authorize item mutations: confirms which user's day plan an item
	// belongs to before a delete/quantity-update is allowed to touch it.
	GetDayPlanItemOwner(ctx context.Context, id uuid.UUID) (GetDayPlanItemOwnerRow, error)
	GetDayPlanTotals(ctx context.Context, dayPlanID uuid.UUID) ([]GetDayPlanTotalsRow, error)
	// Export/import's natural-key lookup for manually-entered meals, which have
	// no source_ref to match on (GetMealBySourceRef doesn't fit: source_ref is
	// NULL for these, not an empty string).
	GetManualMealByName(ctx context.Context, name string) (Meal, error)
	GetMeal(ctx context.Context, id uuid.UUID) (Meal, error)
	GetMealBySourceRef(ctx context.Context, arg GetMealBySourceRefParams) (Meal, error)
	// Export/import's natural-key lookup - a category's id means nothing across
	// instances, but its name (already unique) does.
	GetMealCategoryByName(ctx context.Context, name string) (MealCategory, error)
	// Export/import's natural-key lookup - a label's id means nothing across
	// instances, but its name (already unique) does.
	GetMealLabelByName(ctx context.Context, name string) (MealLabel, error)
	// id is only used for a brand-new row - on conflict, the existing row keeps
	// its original id.
	GetOrCreateDayPlan(ctx context.Context, arg GetOrCreateDayPlanParams) (DayPlan, error)
	GetSession(ctx context.Context, id uuid.UUID) (GetSessionRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByOIDCSubject(ctx context.Context, oidcSubject sql.NullString) (User, error)
	GetUserNutrientGoals(ctx context.Context, userID uuid.UUID) ([]GetUserNutrientGoalsRow, error)
	IsMealFavoriteForCategory(ctx context.Context, arg IsMealFavoriteForCategoryParams) (bool, error)
	ListAppSettings(ctx context.Context) ([]AppSetting, error)
	// Ordered by id as a final tiebreaker (not just category/item sort_order) so
	// that two items which happen to land on the same sort_order - e.g. from a
	// rare concurrent-insert race - still get a stable, repeatable order across
	// queries instead of appearing to reshuffle on every page load.
	ListDayPlanItems(ctx context.Context, dayPlanID uuid.UUID) ([]ListDayPlanItemsRow, error)
	// Written as >= / <= rather than BETWEEN: sqlc's sqlite engine (v1.31.1)
	// drops the BETWEEN operands from the generated function signature entirely
	// (confirmed bug, not a config issue) while leaving both placeholders in the
	// executed SQL text, so a normal call would pass too few args at runtime.
	ListDayPlansInRange(ctx context.Context, arg ListDayPlansInRangeParams) ([]DayPlan, error)
	ListDefaultDayItems(ctx context.Context, userID uuid.UUID) ([]ListDefaultDayItemsRow, error)
	// Batched (not one query per meal) favorite-category lookup for a list of
	// meals - the Meal Library list page's badges, fetched in one round trip
	// regardless of how many meals are on the page.
	ListFavoriteCategoriesForMeals(ctx context.Context, mealIds []uuid.UUID) ([]ListFavoriteCategoriesForMealsRow, error)
	// The favorited category ids for one meal - used to pre-check the edit
	// form's category checkboxes.
	ListFavoriteCategoryIDsForMeal(ctx context.Context, mealID uuid.UUID) ([]uuid.UUID, error)
	ListFavoriteMealsForCategory(ctx context.Context, categoryID uuid.UUID) ([]Meal, error)
	ListMealCategories(ctx context.Context) ([]MealCategory, error)
	// The assigned label ids for one meal - used to pre-check the edit form's
	// label checkboxes.
	ListMealLabelIDsForMeal(ctx context.Context, mealID uuid.UUID) ([]uuid.UUID, error)
	ListMealLabels(ctx context.Context) ([]MealLabel, error)
	// Batched (not one query per meal) label lookup for a list of meals - the
	// Meal Library list page's badges, fetched in one round trip regardless of
	// how many meals are on the page.
	ListMealLabelsForMeals(ctx context.Context, mealIds []uuid.UUID) ([]ListMealLabelsForMealsRow, error)
	ListMealNutrientValues(ctx context.Context, mealID uuid.UUID) ([]ListMealNutrientValuesRow, error)
	ListMeals(ctx context.Context, limitCount int32) ([]Meal, error)
	ListMealsByLabel(ctx context.Context, arg ListMealsByLabelParams) ([]Meal, error)
	ListNutrients(ctx context.Context) ([]Nutrient, error)
	ListUsers(ctx context.Context) ([]User, error)
	RemoveDayPlanItem(ctx context.Context, id uuid.UUID) error
	RemoveDefaultDayItem(ctx context.Context, arg RemoveDefaultDayItemParams) (int64, error)
	RemoveMealFavoriteCategory(ctx context.Context, arg RemoveMealFavoriteCategoryParams) error
	// query is a pre-built trigram-OR FTS5 match expression (see internal/mealslib),
	// not the raw user string - MATCH syntax is passed as a bound parameter, never
	// string-concatenated into the query text.
	SearchMeals(ctx context.Context, arg SearchMealsParams) ([]Meal, error)
	// See SearchMeals for why query is a pre-built trigram-OR match expression.
	SearchMealsByLabel(ctx context.Context, arg SearchMealsByLabelParams) ([]Meal, error)
	SetAppSetting(ctx context.Context, arg SetAppSettingParams) error
	// Drag-and-drop reorder: re-numbering every category's position without
	// touching its name, unlike UpdateMealCategory which requires both.
	SetMealCategorySortOrder(ctx context.Context, arg SetMealCategorySortOrderParams) error
	SetMealNutrientValue(ctx context.Context, arg SetMealNutrientValueParams) error
	SetUserNutrientGoal(ctx context.Context, arg SetUserNutrientGoalParams) error
	UpdateDayPlanItemQuantity(ctx context.Context, arg UpdateDayPlanItemQuantityParams) error
	UpdateMeal(ctx context.Context, arg UpdateMealParams) (Meal, error)
	UpdateMealCategory(ctx context.Context, arg UpdateMealCategoryParams) (MealCategory, error)
	UpdateMealLabel(ctx context.Context, arg UpdateMealLabelParams) (MealLabel, error)
	// id is only used for a brand-new row - on conflict, the existing row keeps
	// its original id (DO UPDATE below never touches the id column).
	UpsertMealBySourceRef(ctx context.Context, arg UpsertMealBySourceRefParams) (Meal, error)
}

var _ Querier = (*Queries)(nil)
