// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlite

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, expires_at)
VALUES (?, ?, ?)
RETURNING id, user_id, created_at, expires_at
`

type CreateSessionParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.ID, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, oidc_subject, email, display_name)
VALUES (?, ?, ?, ?)
RETURNING id, oidc_subject, email, display_name, created_at, password_hash, is_admin
`

type CreateUserParams struct {
	ID          uuid.UUID      `json:"id"`
	OidcSubject sql.NullString `json:"oidc_subject"`
	Email       string         `json:"email"`
	DisplayName sql.NullString `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.OidcSubject,
		arg.Email,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSubject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.IsAdmin,
	)
	return i, err
}

const createUserWithPassword = `-- name: CreateUserWithPassword :one
INSERT INTO users (id, email, password_hash, display_name, is_admin)
VALUES (?, ?, ?, ?, ?)
RETURNING id, oidc_subject, email, display_name, created_at, password_hash, is_admin
`

type CreateUserWithPasswordParams struct {
	ID           uuid.UUID      `json:"id"`
	Email        string         `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	DisplayName  sql.NullString `json:"display_name"`
	IsAdmin      bool           `json:"is_admin"`
}

func (q *Queries) CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUserWithPassword,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSubject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.IsAdmin,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT sessions.id, sessions.user_id, sessions.created_at, sessions.expires_at, users.email, users.display_name, users.oidc_subject, users.is_admin
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.id = ? AND sessions.expires_at > CURRENT_TIMESTAMP
`

type GetSessionRow struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	CreatedAt   time.Time      `json:"created_at"`
	ExpiresAt   time.Time      `json:"expires_at"`
	Email       string         `json:"email"`
	DisplayName sql.NullString `json:"display_name"`
	OidcSubject sql.NullString `json:"oidc_subject"`
	IsAdmin     bool           `json:"is_admin"`
}

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Email,
		&i.DisplayName,
		&i.OidcSubject,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, oidc_subject, email, display_name, created_at, password_hash, is_admin FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSubject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, oidc_subject, email, display_name, created_at, password_hash, is_admin FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSubject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByOIDCSubject = `-- name: GetUserByOIDCSubject :one
SELECT id, oidc_subject, email, display_name, created_at, password_hash, is_admin FROM users WHERE oidc_subject = ?
`

func (q *Queries) GetUserByOIDCSubject(ctx context.Context, oidcSubject sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByOIDCSubject, oidcSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSubject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.IsAdmin,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, oidc_subject, email, display_name, created_at, password_hash, is_admin FROM users ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.OidcSubject,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
			&i.PasswordHash,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
